spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: saad4110
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: saadqayyum4110@gmail.com
    password: !**********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  mail:
#    host: localhost
#    port: 1025
#    username: saadqayyum4110@gmail.com
#    password: yjqequupyqnwsklu
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
#  file:
#    uploads:
#      photos-output-path: ./uploads
server:
  port: 8088